### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by keithbriggs** [mayorx/hungarian-algorithm#2]
```
kbriggs@Z230-work:~/Downloads/hungarian-algorithm-master> python3 demo.py 
Traceback (most recent call last):
  File "demo.py", line 24, in <module>
    matcher = KMMatcher([
  File "/home/kbriggs/Downloads/hungarian-algorithm-master/km_matcher.py", line 21, in __init__
    self.xy = -np.ones((self.n,), dtype=np.int)
  File "/home/kbriggs/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by PortianLiu** [comment]
代码用了 py2.x 时代的语法，说不定是这个原因
